### ISSUE TITLE
Did you report to Espressif ?

### ISSUE THREAD

**Issue by X-Ryl669** [Matheus-Garbelini/esp32_esp8266_attacks#1]
Nice work so far. Did you report these to Espressif? Is it fixed in the latest IDF ?

**Comment by R-INYURU** [comment]
Here is a link for [Bug Bounty](https://www.esp32.com/viewtopic.php?f=10&t=1572) for ESP32 latest ESP-IDF.
You will be rewarded with $500.
Don't miss it.

**Comment by Matheus-Garbelini** [comment]
Hello @R-INYURU and @X-Ryl669. The vulnerabilities reporting have followed responsible disclosure. Espressif has already patched such problems in the latest SDKs of both ESP32 and ESP8266. You can check in the readme of this repositories the links for more information of the merges. I'll update later this repo with the exact disclosure dates but it was given Espressif about 4 months so they could have fixed everything without rushing.
